// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJq7FfAJ9gsLbISDphjdWqObXtS6cGv0A',
    appId: '1:555916327350:web:8a8605c9b8f64f5a366917',
    messagingSenderId: '555916327350',
    projectId: 'fooddelivery-783d4',
    authDomain: 'fooddelivery-783d4.firebaseapp.com',
    storageBucket: 'fooddelivery-783d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBY5WFFplGXunU_qYEvczJwSdIwTKPI5g',
    appId: '1:555916327350:android:72ec26c895464c53366917',
    messagingSenderId: '555916327350',
    projectId: 'fooddelivery-783d4',
    storageBucket: 'fooddelivery-783d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBdYIOB6lnrnBOLQ3OVckv2MLSHQXTQXg',
    appId: '1:555916327350:ios:39fe7f0aae0b0a96366917',
    messagingSenderId: '555916327350',
    projectId: 'fooddelivery-783d4',
    storageBucket: 'fooddelivery-783d4.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBdYIOB6lnrnBOLQ3OVckv2MLSHQXTQXg',
    appId: '1:555916327350:ios:39fe7f0aae0b0a96366917',
    messagingSenderId: '555916327350',
    projectId: 'fooddelivery-783d4',
    storageBucket: 'fooddelivery-783d4.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJq7FfAJ9gsLbISDphjdWqObXtS6cGv0A',
    appId: '1:555916327350:web:e9bf2e028e004dfb366917',
    messagingSenderId: '555916327350',
    projectId: 'fooddelivery-783d4',
    authDomain: 'fooddelivery-783d4.firebaseapp.com',
    storageBucket: 'fooddelivery-783d4.appspot.com',
  );
}
